server:
  port: 8899 #修改tomcat的默认的端口号，将8080改为8888
  #context-path: /cms
  #error:
  #  path: /error # 错误页，指定发生错误时，跳转的URL。请查看BasicErrorController源码便知
  #session-timeout: 60 # session最大超时时间(分钟)，默认为30
  #address: 192.168.0.3 # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败，只有特殊需求的情况下才配置

#本项目的自定义配置
im:
  houoy: www.houoy.com
  date: 2017-02-23
